import React from 'react';
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Box,
  IconButton,
  Typography,
  Alert,
} from '@mui/material';
import {
  Close as CloseIcon,
  OpenInNew as OpenInNewIcon,
  Download as DownloadIcon,
} from '@mui/icons-material';
import type { InfographicData } from '../types';

interface InfographicViewerProps {
  infographic: InfographicData | null;
  open: boolean;
  onClose: () => void;
}

const InfographicViewer: React.FC<InfographicViewerProps> = ({
  infographic,
  open,
  onClose,
}) => {
  const handleOpenInNewTab = () => {
    if (!infographic) return;
    
    const blob = new Blob([infographic.htmlCode], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    
    // Clean up the URL after a delay
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  const handleDownload = () => {
    if (!infographic) return;
    
    const blob = new Blob([infographic.htmlCode], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `infographic-${infographic.id}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!infographic) {
    return null;
  }

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="lg"
      fullWidth
      sx={{
        '& .MuiDialog-paper': {
          height: '90vh',
          maxHeight: '90vh',
        },
      }}
    >
      <DialogTitle sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Typography variant="h6">
          📊 Infographic Viewer
        </Typography>
        <IconButton onClick={onClose} size="small">
          <CloseIcon />
        </IconButton>
      </DialogTitle>
      
      <DialogContent sx={{ p: 0, position: 'relative' }}>
        <Alert severity="info" sx={{ m: 2, mb: 1 }}>
          <Typography variant="body2">
            Interactive infographic generated by the SWOT analysis agent. 
            You can interact with the content below or open it in a new tab for full-screen viewing.
          </Typography>
        </Alert>
        
        <Box
          sx={{
            height: 'calc(100% - 80px)',
            border: '1px solid',
            borderColor: 'divider',
            borderRadius: 1,
            m: 2,
            overflow: 'hidden',
          }}
        >
          <iframe
            srcDoc={infographic.htmlCode}
            style={{
              width: '100%',
              height: '100%',
              border: 'none',
            }}
            title={`Infographic ${infographic.id}`}
            sandbox="allow-scripts allow-same-origin allow-forms"
          />
        </Box>
      </DialogContent>
      
      <DialogActions sx={{ justifyContent: 'space-between', px: 3, pb: 2 }}>
        <Typography variant="caption" color="text.secondary">
          Infographic ID: {infographic.id}
        </Typography>
        <Box>
          <Button
            startIcon={<OpenInNewIcon />}
            onClick={handleOpenInNewTab}
            variant="outlined"
            size="small"
            sx={{ mr: 1 }}
          >
            Open in New Tab
          </Button>
          <Button
            startIcon={<DownloadIcon />}
            onClick={handleDownload}
            variant="outlined"
            size="small"
            sx={{ mr: 1 }}
          >
            Download HTML
          </Button>
          <Button onClick={onClose} variant="contained" size="small">
            Close
          </Button>
        </Box>
      </DialogActions>
    </Dialog>
  );
};

export default InfographicViewer;
